### ISSUE TITLE
where did the impact website go?

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_impact#1]
www_ ... repo for the impact website

**Comment by christopherhutton** [comment]
https://github.com/threefoldfoundation/archived/tree/master/www/www_impact

**Comment by christopherhutton** [comment]
not sure why it was archived to be honest... but the source data is there. I see the site is not available so asked roel to check why ? Let me know if you want it reinstated/fixed now or if you plan to revise the site completely and re-launch the site on the grid . `?

**Comment by VonSub** [comment]
was told by @despiegk to take that out of the footer of threefold.io for now since Impact had no priority. (during our meeting face to face in Ghent beginning FEB)
